// Code generated by "stringer -type=Kind"; DO NOT EDIT.

package block

import "strconv"

const (
	_Kind_name_0 = "DecimalKindStringKind"
	_Kind_name_1 = "BoolKind"
	_Kind_name_2 = "TimeKind"
	_Kind_name_3 = "BlockKind"
	_Kind_name_4 = "NullKind"
	_Kind_name_5 = "AtomKind"
	_Kind_name_6 = "AnyKind"
)

var (
	_Kind_index_0 = [...]uint8{0, 11, 21}
)

func (i Kind) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _Kind_name_0[_Kind_index_0[i]:_Kind_index_0[i+1]]
	case i == 4:
		return _Kind_name_1
	case i == 8:
		return _Kind_name_2
	case i == 16:
		return _Kind_name_3
	case i == 32:
		return _Kind_name_4
	case i == 47:
		return _Kind_name_5
	case i == 63:
		return _Kind_name_6
	default:
		return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
