// Code generated by "stringer -type=Kind"; DO NOT EDIT.

package block

import "strconv"

const (
	_Kind_name_0 = "DecimalKindStringKind"
	_Kind_name_1 = "BoolKind"
	_Kind_name_2 = "TimeKind"
	_Kind_name_3 = "NullKind"
	_Kind_name_4 = "AtomKindListKind"
	_Kind_name_5 = "MapKind"
	_Kind_name_6 = "BlockKind"
	_Kind_name_7 = "CollectionKind"
	_Kind_name_8 = "AnyKind"
)

var (
	_Kind_index_0 = [...]uint8{0, 11, 21}
	_Kind_index_4 = [...]uint8{0, 8, 16}
)

func (i Kind) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _Kind_name_0[_Kind_index_0[i]:_Kind_index_0[i+1]]
	case i == 4:
		return _Kind_name_1
	case i == 8:
		return _Kind_name_2
	case i == 16:
		return _Kind_name_3
	case 31 <= i && i <= 32:
		i -= 31
		return _Kind_name_4[_Kind_index_4[i]:_Kind_index_4[i+1]]
	case i == 64:
		return _Kind_name_5
	case i == 128:
		return _Kind_name_6
	case i == 224:
		return _Kind_name_7
	case i == 255:
		return _Kind_name_8
	default:
		return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
